# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f4d99cd4e07cef1ef3a89fe7645a11430c6904389d3335c8309590b25d27cf673f4ae5f7dacacdc6c6b42c53bcdcdae71b1a0b621272489bbfff716ed64290b

test:
  secret_key_base: 6a27e7dbacc9aaf425596bf917190e705cb3ae0043b09991bb7ae01e7ab1fe07893cc6f790feb092a711fb4e3608204bf05b7da7b5f10bdd9139e877aeacd027

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
